Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "worker2"

  config.vm.network "private_network", ip: "192.168.1.5"
  # config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provision "shell", path: "../provision_nodes.sh"

  config.vm.provider "virtualbox" do |vb|
      # vb.gui = true
      vb.memory = "1024"
      vb.cpus = 1
  end
end
