Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "control"

  config.vm.network "private_network", ip: "192.168.1.2"
  # config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "./data", "/home/vagrant/data"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    # vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
  end
end
